import pytz,datetime
year=int(input("Enter year: "))
month=int(input("Enter Month: "))
day=int(input("Enter date: "))
hour=int(input("Enter hour: "))
minute=int(input("Enter minute: "))
#converting to a date
users_time=datetime.datetime(year,month,day,hour,minute)
print(users_time.isoformat())
cairo_timezone=pytz.timezone('Africa/cairo')
london_timezone=pytz.timezone('UTC')
delhi_timezone=pytz.timezone('Asia/Kolkata')
Sydney_timezone=pytz.timezone('Australia/Sydney')
Tokyo_timezone=pytz.timezone('Asia/Tokyo')
Seoul_timezone=pytz.timezone('Asia/Seoul')

cairo_time=pytz.utc.localize(users_time).astimezone(cairo_timezone)
london_time=pytz.utc.localize(users_time).astimezone(london_timezone)
delhi_timez=pytz.utc.localize(users_time).astimezone(delhi_timezone)
Sydney_time=pytz.utc.localize(users_time).astimezone(Sydney_timezone)
Tokyo_time=pytz.utc.localize(users_time).astimezone(Tokyo_timezone)
Seoul_time=pytz.utc.localize(users_time).astimezone(Seoul_timezone)
print("Cairo Time is ",cairo_time.isoformat())
print("London Time is ",london_time.isoformat())
print("New Delhi Time is ",delhi_timez.isoformat())
print("Sydney Time is ",Sydney_time.isoformat())
print("Tokyo Time is ",Tokyo_time.isoformat())
print("Seoul Time is ",Seoul_time.isoformat())

