clc;
close all;
clear all;
a=imread('clock.jpg');
k=imgaussfilt(a);
l=imgaussfilt(a,1);
m=imgaussfilt(a,3);
n=imgaussfilt(a,5);
o=imgaussfilt(a,10);
sgtitle("Image Blurring");
subplot(3,2,1);imshow(a);title('original image');
subplot(3,2,2);imshow(k);
title('Blurred image by guassian filter with standard deviation (sigma= 0.5)');
subplot(3,2,3);imshow(l);
title('Blurred image by guassian filter with standard deviation (sigma= 1)');
subplot(3,2,4);imshow(m);
title('Blurred image by guassian filter with standard deviation (sigma= 3)');
subplot(3,2,5);imshow(n);
title('Blurred image by guassian filter with standard deviation (sigma= 5)');
subplot(3,2,6);imshow(o);
title('Blurred image by guassian filter with standard deviation (sigma= 10)');